; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pcb
 
[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi
framework = arduino 
extra_scripts=pre:add_git_branch.py
board = seeed_xiao_rp2350	# seeed_xiao_rp2040 
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m 
build_flags = 
	-DUSE_TINYUSB
	-DUSB_MIDI_VID=0x1337
	-DUSB_MIDI_PID=0xBEEF
	-DUSB_MIDI_MANUFACTURER="\"TyrellCorp\""
	-DUSB_MIDI_PRODUCT="\"Microlidian\""
	-DUSE_DINMIDI
	-DSTOP_WHILE_STOPPED_REWINDS
	-DMIDI_SERIAL_SPIO
	-DMIDI_SERIAL_OUT_PIN=D6
	-DENCODER_DURING_SETUP
	-DENABLE_SCREEN
	-DENABLE_REMOTE_VIEWER
	-DTFT_BODMER
	-DBODMER_SPRITE
	;-DDISPLAY_RGB332_FB_MODE		; A/B test: enable RGB332 internal framebuffer mode
	-DENABLE_LITTLEFS
	;-DDEBUG_RP2040_PORT=Serial			; for debugging LittleFS
	-DENABLE_CALIBRATION_STORAGE
	-DLOAD_CALIBRATION_ON_BOOT
	-DFAST_VOLTAGE_READS
	-DENABLE_CLOCK_INPUT_CV
	-DPARAMETER_INPUT_GRAPH_HEIGHT=40
	-DDISABLE_PARAMETER_INPUT_SELECTORS	; don't allow changing parameter slot inputs -- saves 50K of RAM while we come up with a better way to do this
	-DPARAMETER_INPUTS_USE_OUTPUT_POLARITY
	;-DPARAMETER_INPUTS_USE_CALLBACKS
	-DALT_MENU_POSITIONING				; use alternate mymenu positioning logic
	-DRP2040_PIO_SPI
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DSCREEN_ROTATION=3
	-DTFT_SCLK=D8
	-DTFT_MOSI=D10
	-DTFT_MISO=-1
	-DTFT_CS=D7
	-DTFT_RST=-1
	;-DTFT_DC=D0			;; breadboard version has DC on D0 and back button on D9
	-DTFT_DC=D9
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-DLOAD_FONT6=1
	-DLOAD_FONT7=1
	-DLOAD_FONT8=1
	-DLOAD_FONT8N=1
	-DLOAD_GFXFF
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=50000000
	-DFLASHMEM=""	; for compatibility with Teensy code that expects FLASHMEM
	-DFASTRUN=""	; for compatibility with Teensy code that expects FASTRUN
lib_ignore = SD
lib_deps = 
	;SD
	LittleFS
	Encoder
	Bounce2
	MIDI Library
	;adafruit/Adafruit TinyUSB Library
	Adafruit TinyUSB Library=https://github.com/doctea/Adafruit_TinyUSB_Arduino
	vortigont/LinkedList
	mymenu
	midihelpers
	RobTillaart/ADS1X15@^0.4.5
	RobTillaart/DAC8574
	parameters
	saveloadlib
	ArxTypeTraits
	khoih-prog/Functional-Vlpp@^1.0.2		; TODO: specify doctea fork here
	ArduinoHashtable=https://github.com/braydenanderson2014/ArduinoHashtable
	; SimpleVector=https://github.com/doctea/SimpleVector
lib_extra_dirs =  
	lib
	C:\Users\doctea\Documents\Arduino\my_libraries
upload_port = COM5
monitor_port = COM5
debug_extra_cmds =
    set remotetimeout 60
[env:pcb]
; comment out these lines if not using raspberry debug probe
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
;debug_speed = 10000
;upload_speed = 10000
BUILD_TYPE=debug
debug_build_flags = -O0 -g -ggdb
build_flags = 
	;-DENABLE_PROFILING
	;-DCFG_TUD_CDC=0
	-DUSE_UCLOCK
	;-DUSE_UCLOCK_GENERIC
	-DENABLE_REMOTE_VIEWER
	-DUSE_TINYUSB
	-DUSB_MIDI_VID=0x1337
	-DUSB_MIDI_PID=0xBEEF
	-DUSB_MIDI_MANUFACTURER="\"TyrellCorp\""
	-DUSB_MIDI_PRODUCT="\"Microlidian\""
	-DUSE_DINMIDI
	-DSTOP_WHILE_STOPPED_REWINDS
	-DMIDI_SERIAL_SPIO
	;-DMIDI_SERIAL_HARDWARE
	-DMIDI_SERIAL_OUT_PIN=D6
	-DBUILD_PCB
	-DENABLE_BUTTON_MATRIX
	-DENCODER_DURING_SETUP
	-DENABLE_TIME_SIGNATURE
	-DENABLE_EUCLIDIAN
	-DENABLE_ACCENTS
	-DENABLE_ENVELOPES
	-DENABLE_ENVELOPES_AS_PARAMETER_INPUTS
	-DChosenDrumKitMIDIOutputProcessor=FullDrumKitAndBassAndChordsMIDIOutputProcessor ;FullDrumKitAndBassMIDIOutputProcessor
	-DENABLE_SCALES
	-DENABLE_SHUFFLE
	-DENABLE_ARRANGER
	-DENABLE_PARAMETERS
	-DENABLE_EXTENDED_VIRTUAL_INPUTS
	-DENABLE_SCREEN
	;-DENABLE_CV_INPUT=0x48	; default i2c address is 0x48, but that conflicts with the DAC8574 broadcast address!
	-DENABLE_CV_INPUT=0x49
	;-DENABLE_CV_OUTPUT=0x4E
	;-DENABLE_CV_OUTPUT_BANK=1
	; -DDISABLE_CV_INPUT_CAL_WIZARD
	-DTFT_BODMER
	;-DBODMER_SPRITE_8BIT
	-DBODMER_SPRITE
	; -DDISPLAY_RGB332_FB_MODE		; A/B test: enable RGB332 internal framebuffer mode
	; -DDISPLAY_RGB332_DMA_PINGPONG=1	; overlap conversion with DMA using two stage buffers
	; -DDISPLAY_RGB332_DIRTY_FLUSH=1	; questionable whether this brings benefits
	; -DDISPLAY_RGB332_DMA_CHUNK_LINES=16	; tuning: test if better feel vs chunk_lines=16
	; -DMENU_PERF_PARTIAL_UPDATES=1	; A/B: skip redraw for static menu items (experimental)
	; -DREMOTE_VIEWER_LIVE_MAX_FPS=10	; increase from 8 to reduce throttling impact
	-DENABLE_STORAGE
	-DENABLE_LITTLEFS
	;;-DDEBUG_RP2040_PORT=Serial			; for debugging LittleFS
	-DENABLE_CALIBRATION_STORAGE
	-DPARAMETER_INPUTS_USE_CALLBACKS
	-DLOAD_CALIBRATION_ON_BOOT
	-DFAST_VOLTAGE_READS
	-DENABLE_CLOCK_INPUT_CV
	-DPARAMETER_INPUT_GRAPH_HEIGHT=40
	;-DDISABLE_PARAMETER_INPUT_SELECTORS
	-DALT_MENU_POSITIONING				; use alternate mymenu positioning logic
	-DRP2040_PIO_SPI
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DSCREEN_ROTATION=1
	-DTFT_SCLK=D8
	-DTFT_MOSI=D10
	-DTFT_MISO=-1
	-DTFT_CS=D7
	-DTFT_RST=-1
	;-DTFT_DC=D0			;; breadboard version has DC on D0 and back button on D9
	-DTFT_DC=D9
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DLOAD_GLCD=1
	;-DLOAD_FONT2=1
	;-DLOAD_FONT4=1
	;-DLOAD_FONT6=1
	;-DLOAD_FONT7=1
	;-DLOAD_FONT8=1
	;-DLOAD_FONT8N=1
	-DLOAD_GFXFF=1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=50000000
	-DFLASHMEM=""	; for compatibility with Teensy code that expects FLASHMEM
	-DFASTRUN=""	; for compatibility with Teensy code that expects FASTRUN
upload_port = COM5
monitor_port = COM5
lib_archive = no
lib_ignore = SD
lib_deps = 
	SimplyAtomic=https://github.com/wizard97/SimplyAtomic
	LittleFS
	Encoder
	Bounce2@^2.71
	MIDI Library
	;SD @ 2.0.0
	Adafruit TinyUSB Library=https://github.com/doctea/Adafruit_TinyUSB_Arduino
	vortigont/LinkedList
	mymenu
	midihelpers
	RobTillaart/ADS1X15@^0.5.0
	DAC8574=https://github.com/RobTillaart/DAC8574@^0.1.1
	parameters
	saveloadlib
	seqlib
	ArxTypeTraits
	khoih-prog/Functional-Vlpp@^1.0.2	; TODO: specify doctea fork here
	TFT_eSPI
lib_extra_dirs =  
	lib
	C:\Users\doctea\Documents\Arduino\my_libraries
debug_extra_cmds =
    set remotetimeout 60

[env:megalidian]
board = olimex_pico2bb48r
BUILD_TYPE=debug
debug_build_flags = -O0 -g -ggdb
build_unflags = 
	-DMIDI_SERIAL_SPIO
	-DMIDI_SERIAL_OUT_PIN
build_flags = 

	;;;;; core features
	-DUSE_UCLOCK
	-DENCODER_DURING_SETUP
	-DENABLE_STORAGE
	-DENABLE_LITTLEFS
	;-DDEBUG_RP2040_PORT=Serial			; for debugging LittleFS

	;;;;; USB and MIDI settings
	-DUSE_TINYUSB
	-DUSB_MIDI_VID=0x1337
	-DUSB_MIDI_PID=0xDEAF
	-DUSB_MIDI_MANUFACTURER="\"TyrellCorp\""
	-DUSB_MIDI_PRODUCT="\"Sidian\""
	-DSTOP_WHILE_STOPPED_REWINDS

	;;;;; serial MIDI settings
	; -DUSE_DINMIDI
	; -DMIDI_SERIAL_SPIO
	; -DMIDI_SERIAL_OUT_PIN=D6

	;;;;; system features
	-DENABLE_CALIBRATION_STORAGE
	-DRP2040_PIO_SPI
	-DDISABLE_ALL_LIBRARY_WARNINGS		; hide warnings from tft_epsi library
	;-DENABLE_CLOCK_INPUT_CV

	;;;;; parameter/modulation features
	-DENABLE_PARAMETERS
	-DENABLE_CV_INPUT
	-DFAST_VOLTAGE_READS
	-DENABLE_ENVELOPES
	-DENABLE_ENVELOPES_AS_PARAMETER_INPUTS
	-DENABLE_EXTENDED_VIRTUAL_INPUTS
	-DPARAMETER_INPUT_GRAPH_HEIGHT=40
	-DPARAMETER_INPUTS_USE_CALLBACKS
	-DFAST_VOLTAGE_READS
	-DLOAD_CALIBRATION_ON_BOOT
	; -DDISABLE_PARAMETER_INPUT_SELECTORS
	; -DENABLE_CV_INPUT=0x49

	;;;;; musical features
	-DENABLE_TIME_SIGNATURE
	-DENABLE_ARRANGER
	-DENABLE_SCALES
	
	;; sequencer-related features
	-DChosenDrumKitMIDIOutputProcessor=FullDrumKitAndBassAndChordsMIDIOutputProcessor ;FullDrumKitAndBassMIDIOutputProcessor
	-DENABLE_ACCENTS
	-DENABLE_EUCLIDIAN
	-DENABLE_SHUFFLE

	;; TFT / screen / menu settings
	-DENABLE_SCREEN
	-DTFT_BODMER
	-DBODMER_SPRITE
	-DUSE_DMA
	-DALT_MENU_POSITIONING				; use alternate mymenu positioning logic
	-DENABLE_REMOTE_VIEWER
	-DMENU_PERF_PARTIAL_UPDATES=1	; A/B: skip redraw for static menu items (experimental)

	-DSCREEN_ROTATION=3
	-DTFT_SCLK=D6
	-DTFT_MOSI=D7
	; -DTFT_MISO=D4
	-DTFT_CS=D5
	-DTFT_RST=-1
	-DTFT_DC=D24
	-DTFT_SPI_PORT=0
	;-DTFT_DC=D9
	-DUSER_SETUP_LOADED=1
	-DST7789_2_DRIVER=1
	-DTFT_WIDTH=240 ; 100
	-DTFT_HEIGHT=320
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-DLOAD_FONT6=1
	-DLOAD_FONT7=1
	-DLOAD_FONT8=1
	-DLOAD_FONT8N=1
	-DLOAD_GFXFF=1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=25000000

	-DFLASHMEM=""	; for compatibility with Teensy code that expects FLASHMEM
	-DFASTRUN=""	; for compatibility with Teensy code that expects FASTRUN

	-DBUILD_BREADBOARD

upload_port = \\.\COM10
upload_protocol = cmsis-dap
monitor_port = \\.\COM10
debug_tool = cmsis-dap

; board_build.pico_boot2_name = boot2_psram8.S
; board_build.pico_psram_size = 8
; board_upload.psram_length = 8388608

lib_ignore = SD
lib_extra_dirs =  
	lib
	C:\Users\doctea\Documents\Arduino\my_libraries
lib_deps = 
	;; core support libraries
	SimplyAtomic=https://github.com/wizard97/SimplyAtomic
	vortigont/LinkedList
	;SD @ 2.0.0
	LittleFS
	Encoder
	TFT_eSPI
	Bounce2@^2.71
	MIDI Library
	Adafruit TinyUSB Library=https://github.com/doctea/Adafruit_TinyUSB_Arduino
	ArxTypeTraits
	khoih-prog/Functional-Vlpp@^1.0.2	; TODO: specify doctea fork here

	;; hardware support libraries
	RobTillaart/ADS1X15@^0.5.0
	DAC8574=https://github.com/RobTillaart/DAC8574@^0.1.1

	;; my custom libraries
	mymenu
	midihelpers
	parameters
	saveloadlib
	seqlib