; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = microlidian_pcb
 
;; shared configuration
[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi
framework = arduino 
extra_scripts=pre:add_git_branch.py
board = seeed_xiao_rp2350	# seeed_xiao_rp2040 
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m 

debug_tool = cmsis-dap
upload_protocol = cmsis-dap
debug_build_flags = -O0 -g -ggdb
upload_port = COM5
monitor_port = COM5

lib_ignore = SD			; might actually want to make this env-specific later if we end up using SD on the megalidian
lib_archive = no
lib_extra_dirs =  
	lib
	C:\Users\doctea\Documents\Arduino\my_libraries
lib_deps = 
	;; core support libraries
	Adafruit TinyUSB Library=https://github.com/adafruit/Adafruit_TinyUSB_Arduino 
	; Adafruit TinyUSB Library=https://github.com/doctea/Adafruit_TinyUSB_Arduino
	ArxTypeTraits
	Bounce2@^2.71
	Encoder
	LittleFS
	khoih-prog/Functional-Vlpp@^1.0.2	; TODO: specify doctea fork here
	MIDI Library
	;SD @ 2.0.0
	SimplyAtomic=https://github.com/wizard97/SimplyAtomic
	vortigont/LinkedList

	;; hardware support libraries
	DAC8574=https://github.com/RobTillaart/DAC8574@^0.1.1
	RobTillaart/ADS1X15@^0.5.0
	TFT_eSPI

	;; my custom libraries
	midihelpers
	mymenu
	parameters
	saveloadlib
	seqlib
;; Microlidian PCB specific configuration 
[env:microlidian_pcb]

BUILD_TYPE=debug
debug_build_flags = -O0 -g -ggdb
build_flags = 
	;;;;; Signal build type to any config within source
	;;; eg, there is still in Config.h that determines button pins etc
	-DBUILD_MICROLIDIAN_PCB

	;;;;; debug features
	; -DENABLE_PROFILE_ON_STARTUP

	;;;;; core features
	-DUSE_UCLOCK
	-DENCODER_DURING_SETUP
	-DENABLE_STORAGE
	-DENABLE_LITTLEFS
	;-DDEBUG_RP2040_PORT=Serial			; for debugging LittleFS
	-DENABLE_BUTTON_MATRIX

	;;;;; USB settings
	-DUSE_TINYUSB
	-DUSB_MIDI_VID=0x1337
	-DUSB_MIDI_PID=0xBEEF
	-DUSB_MIDI_MANUFACTURER="\"TyrellCorp\""
	-DUSB_MIDI_PRODUCT="\"Microlidian\""

	;;;;; MIDI settings
	;;; Serial
	-DUSE_DINMIDI
	-DMIDI_SERIAL_SPIO
	-DMIDI_SERIAL_OUT_PIN=D6
	;-DMIDI_SERIAL_HARDWARE
	;;; General
	-DSTOP_WHILE_STOPPED_REWINDS

	;;;;; system features
	-DENABLE_CALIBRATION_STORAGE
	-DRP2040_PIO_SPI
	-DDISABLE_ALL_LIBRARY_WARNINGS		; hide warnings from tft_epsi library
	;-DENABLE_CLOCK_INPUT_CV
	-DENABLE_REMOTE_VIEWER

	;;;;; parameter/modulation features
	-DENABLE_PARAMETERS
	-PROCESS_PARAMETERS_ON_CORE_0		; process parameters updates on core 0 (if not set, processes on core 1 instead); this seems to give us much better ParameterInputDisplay (sharp peaks don't get cut sometimes..)
	-DPARAMETERS_MS_BETWEEN_UPDATES=5   ; MS between CV/parameter processing; TODO: worth experimenting with lower values here, and figuring out which core is idle more?
	-DFAST_VOLTAGE_READS
	-DPARAMETER_INPUTS_USE_CALLBACKS
	-DVOLTAGE_SOURCE_DEFAULT_SMOOTHING=0.5f	;; default smoothing for voltage sources; this is a good balance between responsiveness and noise reduction for CV inputs, especially when using the ADS24vVoltageSource which can be a bit noisy.  we can always override this per voltage source if we want.

	-DENABLE_EXTENDED_VIRTUAL_INPUTS
	-DEXTENDED_VIRTUALS_AS_LIGHTWEIGHT=true		;; not enough RAM on basic RP2350 boards to use full featured extended virtuals
	-DPARAMETER_INPUT_GRAPH_HEIGHT=40

	-DLOAD_CALIBRATION_ON_BOOT
	;-DENABLE_CV_INPUT=0x48	; default i2c address is 0x48, but that conflicts with the DAC8574 broadcast address!
	-DENABLE_CV_INPUT=0x49
	;-DENABLE_CV_OUTPUT=0x4E			;; experimental CV Output support
	;-DENABLE_CV_OUTPUT_BANK=1
	; -DDISABLE_CV_INPUT_CAL_WIZARD		;; disable the CV input calibration wizard if we don't have enough RAM for it
	;;; Envelopes
	-DENABLE_ENVELOPES
	-DENABLE_ENVELOPES_AS_PARAMETER_INPUTS

	;;;;; musical features
	-DENABLE_ARRANGER
	-DENABLE_SCALES
	-DENABLE_TIME_SIGNATURE
	;; sequencer-related features
	-DChosenDrumKitMIDIOutputProcessor=FullDrumKitAndBassAndChordsMIDIOutputProcessor ;FullDrumKitAndBassMIDIOutputProcessor
	-DENABLE_ACCENTS
	-DENABLE_EUCLIDIAN
	-DENABLE_SHUFFLE
	; -DNUMBER_SHUFFLE_PATTERNS=2

	;;;; TFT / screen / menu settings
	-DENABLE_SCREEN
	-DTFT_BODMER
	-DBODMER_SPRITE
	-DUSE_DMA
	-DENABLE_REMOTE_VIEWER
	; -DMENU_PERF_PARTIAL_UPDATES=1	; seems we have not enough RAM for this on basic RP2350.  only redraw/send over DMA the parts of screen that have changed; this is a big performance boost, especially for large screens
	-DALT_MENU_POSITIONING			; use alternate mymenu positioning logic

	;; specific settings for target hardware
	-DSCREEN_ROTATION=1
	-DTFT_SCLK=D8
	-DTFT_MOSI=D10
	; -DTFT_MISO=-1
	-DTFT_CS=D7
	-DTFT_RST=-1
	-DTFT_DC=D9
	-DSPI_FREQUENCY=50000000
	-DST7789_DRIVER=1			; ST7789_DRIVER needed for our Microlidian display
	-DTFT_WIDTH=135				; resolution of our smaller screens; its rotated, so width/height are swapped
	-DTFT_HEIGHT=240

	;; generic settings for tft_eSPI
	-DUSER_SETUP_LOADED=1
	-DTFT_SPI_PORT=0
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-DLOAD_FONT6=1
	-DLOAD_FONT7=1
	-DLOAD_FONT8=1
	-DLOAD_FONT8N=1
	-DLOAD_GFXFF=1
	-DSMOOTH_FONT=1
	-DFLASHMEM=""	; for compatibility with Teensy code that expects FLASHMEM
	-DFASTRUN=""	; for compatibility with Teensy code that expects FASTRUN
;; env of [env:pcb]

;; Megalidian specific configuration (currently breadboard version)
[env:megalidian]
;; use def from http://github.com/doctea/platform-raspberrypi where i have added a board definition for the olimex pico2bb48r, which has 8mb of psram and the same pinout as the pico2bb48.  if we end up using a different board, we'll need to update this and potentially some of the build flags below
board = olimex_pico2bb48r
;; these lines below needed if don't have patched version of framework with olimex_pico2bb48r
; board = olimex_pico2bb48
; board_build.pico_boot2_name = boot2_psram8.S
; board_build.pico_psram_size = 8
; board_upload.psram_length = 8388608
board_build.filesystem_size = 2m 
BUILD_TYPE=debug
debug_build_flags = -O0 -g -ggdb
build_unflags = 
	-DMIDI_SERIAL_SPIO
	-DMIDI_SERIAL_OUT_PIN
build_flags = 
	;;;;; Signal build type to any config within source
	;;; eg, there is still in Config.h that determines button pins etc
	-DBUILD_MEGALIDIAN_BREADBOARD
	-DARDUINO_ARCH_RP2350				; doesn't get defined by the board?

	;;;;; debug features
	; -DENABLE_PROFILE_ON_STARTUP

	;;;;; core features
	-DUSE_UCLOCK
	-DENCODER_DURING_SETUP
	-DENABLE_STORAGE
	-DENABLE_LITTLEFS
	;-DDEBUG_RP2040_PORT=Serial			; for debugging LittleFS
	; -DENABLE_BUTTON_MATRIX

	;;;;; USB settings
	-DUSE_TINYUSB
	-DUSB_MIDI_VID=0x1337
	-DUSB_MIDI_PID=0xDEAF
	-DUSB_MIDI_MANUFACTURER="\"TyrellCorp\""
	-DUSB_MIDI_PRODUCT="\"Megalidian\""

	;;;;; MIDI settings
	;;; Serial
	; -DUSE_DINMIDI
	; -DMIDI_SERIAL_SPIO
	; -DMIDI_SERIAL_OUT_PIN=D6
	;;; General
	-DSTOP_WHILE_STOPPED_REWINDS

	;;;;; system features
	-DENABLE_CALIBRATION_STORAGE
	-DRP2040_PIO_SPI
	-DDISABLE_ALL_LIBRARY_WARNINGS		; hide warnings from tft_epsi library
	;-DENABLE_CLOCK_INPUT_CV
	-DENABLE_REMOTE_VIEWER

	;;;;; parameter/modulation features
	-DENABLE_PARAMETERS
	-DPROCESS_PARAMETERS_ON_CORE_0		; process parameters updates on core 0 (if not set, processes on core 1 instead); this seems to give us much better ParameterInputDisplay (sharp peaks don't get cut sometimes..)
	-DPARAMETERS_MS_BETWEEN_UPDATES=3   ; MS between CV/parameter processing; TODO: worth experimenting with lower values here, and figuring out which core is idle more?
	; -DFAST_VOLTAGE_READS
	-DPARAMETER_INPUTS_USE_CALLBACKS
	-DVOLTAGE_SOURCE_DEFAULT_SMOOTHING=0.5f	;; default smoothing for voltage sources; this is a good balance between responsiveness and noise reduction for CV inputs, especially when using the ADS24vVoltageSource which can be a bit noisy.  we can always override this per voltage source if we want.

	-DENABLE_EXTENDED_VIRTUAL_INPUTS
	-DEXTENDED_VIRTUALS_AS_LIGHTWEIGHT=false	; we have enough RAM on this platform to use the full featured extended (ie controls and display)
	-DPARAMETER_INPUT_GRAPH_HEIGHT=40

	-DLOAD_CALIBRATION_ON_BOOT
	; -DENABLE_CV_INPUT=0x48	; default i2c address is 0x48, but that conflicts with the DAC8574 broadcast address!
	-DENABLE_CV_INPUT=0x49				;; actually we use ArduinoPinVoltageSource for CV input on Megalidian breadboard rn so the address is irrelevant, but we still need to define this to activate the functionality
	; -DENABLE_CV_OUTPUT=0x4E			;; experimental CV Output support
	; -DENABLE_CV_OUTPUT_BANK=1
	; -DDISABLE_CV_INPUT_CAL_WIZARD		;; disable the CV input calibration wizard if we don't have enough RAM for it
	;;; Envelopes
	-DENABLE_ENVELOPES
	-DENABLE_ENVELOPES_AS_PARAMETER_INPUTS

	;;;;; musical features
	-DENABLE_TIME_SIGNATURE
	-DENABLE_ARRANGER
	-DENABLE_SCALES
	;; sequencer-related features
	-DChosenDrumKitMIDIOutputProcessor=FullDrumKitAndBassAndChordsMIDIOutputProcessor ;FullDrumKitAndBassMIDIOutputProcessor
	-DENABLE_ACCENTS
	-DENABLE_EUCLIDIAN
	-DENABLE_SHUFFLE
	-DNUMBER_SHUFFLE_PATTERNS=4

	;; TFT / screen / menu settings
	-DENABLE_SCREEN
	-DTFT_BODMER
	-DBODMER_SPRITE
	-DUSE_DMA
	-DENABLE_REMOTE_VIEWER
	-DMENU_PERF_PARTIAL_UPDATES=1	; only redraw/send over DMA the parts of screen that have changed; this is a big performance boost, especially for large screens
	; -DALT_MENU_POSITIONING			; use alternate mymenu positioning logic

	;; specific settings for target hardware
	-DSCREEN_ROTATION=3
	-DTFT_SCLK=D6
	-DTFT_MOSI=D7
	; -DTFT_MISO=D4
	-DTFT_CS=D5
	-DTFT_RST=-1
	-DTFT_DC=D24
	-DSPI_FREQUENCY=29000000	; don't seem to be able to push this higher than 30mhz on breadboard, just starts up with black screen.  maybe better once we get onto PCB? or maybe its the waveshare display thats the issue? since we managed 50mhz on the XIAO RP2350
	-DST7789_2_DRIVER=1			; ST7789_DRIVER needed for Waveshare display
	-DTFT_WIDTH=240				; resolution of our bigger screens; its rotated, so width/height are swapped
	-DTFT_HEIGHT=320

	-DUSER_SETUP_LOADED=1
	-DTFT_SPI_PORT=0
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-DLOAD_FONT6=1
	-DLOAD_FONT7=1
	-DLOAD_FONT8=1
	-DLOAD_FONT8N=1
	-DLOAD_GFXFF=1
	-DSMOOTH_FONT=1
	-DFLASHMEM=""	; for compatibility with Teensy code that expects FLASHMEM
	-DFASTRUN=""	; for compatibility with Teensy code that expects FASTRUN
;; env of [env:megalidian]